//import NexPage type from Next
import type { NextPage } from 'next'
import Head from 'next/head'
// Image next/image component https://nextjs.org/docs/api-reference/next/image
import Image from 'next/image'
//import GetStaticProps type from Next
import { GetStaticProps } from 'next'
import Axios from 'axios'
import styles from '../styles/Home.module.css'
import { CoinInterface } from '../types'
import { useEffect } from 'react'


const Home: NextPage<{ coins : CoinInterface[] }> = ({ coins }) => {


  useEffect(() => {
    console.log('coins', coins )
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>FLIPCOINS</h1>
        <h3>Cryptocurrencies Live Prices</h3>

        <div className={styles.coins__container}>
          {/* map the coins array and render each coin */}
          {
            coins.map(coin => {
              return(
                <div className={styles.coin} key={coin.symbol}>
                  <Image src={coin.icon} alt={coin.symbol} width={25} height={25} />
                  <p>{coin.name}</p>

                  {/* format number into currency format, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat */}
                  <p>{new Intl.NumberFormat('en-US', { style: 'currency', currency: 'usd', currencyDisplay: 'symbol' }).format(coin.price)}</p>
                </div>
              )
            })
          }
        </div>
        

      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home



// Using GetStaticProps (Static Site Generation) method from NextJs to fetch coins data from coinstats API and return coins array as a prop
// https://nextjs.org/docs/basic-features/data-fetching/get-static-props

export const getStaticProps: GetStaticProps = async (context) => {

  // using axios to preform to the fetch
  let res = await Axios.get('https://api.coinstats.app/public/v1/coins?skip=0')
  let coins = res.data.coins

  return {
    props: { coins } // will be passed to the page component as a prop
  }
}
